/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev
 */
public class Course extends javax.swing.JFrame {
    String connectionURl="jdbc:derby://localhost:1527/ExaminationSystem";
    Connection Connection=null;
    PreparedStatement Statement=null;
    ResultSet rs=null;
    
    

    /**
     * Creates new form Course
     */
    public Course() {
        initComponents();
        Fill();
    }
public void Fill()
    {
        try{
            connectionDb.con=connectionDb.getConnection();
            connectionDb.statement=connectionDb.con.createStatement();
            String sql="select CourseName from Course";
            connectionDb.rs=connectionDb.statement.executeQuery(sql);
           JC.removeAllItems();
            JC.addItem("Choose any one");
            while(connectionDb.rs.next())
            {
                JC.addItem(String.valueOf(connectionDb.rs.getString("CourseName")));
            }
        }
         catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CN = new javax.swing.JTextField();
        H = new javax.swing.JTextField();
        M = new javax.swing.JTextField();
        JC = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Course");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 49, 124, 51));

        CN.setBackground(new java.awt.Color(255, 255, 153));
        CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CN.setText("Course Name");
        CN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CNFocusGained(evt);
            }
        });
        CN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CNMouseClicked(evt);
            }
        });
        getContentPane().add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 174, 415, 41));

        H.setBackground(new java.awt.Color(255, 255, 153));
        H.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        H.setText("Time(Hour)");
        H.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HFocusGained(evt);
            }
        });
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 226, 193, 41));

        M.setBackground(new java.awt.Color(255, 255, 153));
        M.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        M.setText("Time(Min)");
        M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MFocusGained(evt);
            }
        });
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 226, 196, 41));

        JC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCItemStateChanged(evt);
            }
        });
        getContentPane().add(JC, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 305, 415, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 174, 131, 93));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 305, 131, 40));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 517, 132, 37));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminControl AC=new AdminControl();
        AC.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CNFocusGained
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_CNFocusGained

    private void HFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HFocusGained
        // TODO add your handling code here:
        H.setText("");
    }//GEN-LAST:event_HFocusGained

    private void CNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CNMouseClicked
        // TODO add your handling code here:
         CN.setText("");
    }//GEN-LAST:event_CNMouseClicked

    private void MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MFocusGained
        // TODO add your handling code here:
        M.setText("");
    }//GEN-LAST:event_MFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();       
             String CouName=CN.getText();
            String hours=H.getText();
            String Min=M.getText();
            
            
            String Sql="insert into Course values(?,?,?)";
            Connection=DriverManager.getConnection(connectionURl,"Akash","Akash");
            Statement=Connection.prepareCall(Sql);
            Statement.setString(1, CouName);
            Statement.setString(2, hours);
            Statement.setString(3, Min);
            Statement.execute();
            this.setVisible(false);
        Course C=new Course();
        C.setVisible(true);
            
            JOptionPane.showMessageDialog(null, "This Course has Been successful Created");
             
         
        }
        catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_JCItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
        String CON=JC.getSelectedItem().toString();
        String sql="delete from Course where CourseName=?";
        Connection=DriverManager.getConnection(connectionURl,"Akash","Akash");
         Statement=Connection.prepareStatement(sql);
      Statement.setString(1, CON);
       Statement.execute();
       String sql2="delete from QueRec where CourseName=?";
       Connection=DriverManager.getConnection(connectionURl,"Akash","Akash");
         Statement=Connection.prepareStatement(sql2);
      Statement.setString(1, CON);
       Statement.execute();
       
       this.setVisible(false);
        Course C=new Course();
        C.setVisible(true);
       JOptionPane.showMessageDialog(null,"The Course has been Delete");
       
        
    }
    catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CN;
    private javax.swing.JTextField H;
    private javax.swing.JComboBox<String> JC;
    private javax.swing.JTextField M;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
