/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev
 */
public class UserRecord extends javax.swing.JFrame {
    
     String connectionURl="jdbc:derby://localhost:1527/ExaminationSystem";

        PreparedStatement ps=null;
        Connection connection=null;
        ResultSet rs=null;

    /**
     * Creates new form StudentRecord
     */
    public UserRecord() {
        initComponents();
        PR.setVisible(false);
       
    }
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MO = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        SEM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ADD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Gender = new javax.swing.JTextField();
        PR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CN = new javax.swing.JTextArea();
        UNP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Student Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 27, 278, 28));

        UN.setEditable(false);
        jPanel1.add(UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 225, 29));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 109, 29));
        jPanel1.add(PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 278, 29));

        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 27));
        jPanel1.add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 224, 27));

        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 109, 27));
        jPanel1.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 278, 31));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 123, 31));

        jLabel7.setText("Mobile");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 109, 31));

        jLabel8.setText("DOB");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 111, 29));
        jPanel1.add(MO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 278, 31));
        jPanel1.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 224, 29));

        jLabel9.setText("SEM");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 120, 29));

        SEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMActionPerformed(evt);
            }
        });
        jPanel1.add(SEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 280, 29));

        jLabel11.setText("College Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 120, 28));
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 680, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 134, 33));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 152, 33));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Modify Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 172, 33));
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 224, 31));

        PR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PRFocusGained(evt);
            }
        });
        PR.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PRPropertyChange(evt);
            }
        });
        jPanel1.add(PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 150, 30));

        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 136, 29));

        jLabel12.setText("Address");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 124, 32));

        CN.setColumns(20);
        CN.setRows(5);
        jPanel1.add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 690, -1));

        UNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background.png"))); // NOI18N
        jPanel1.add(UNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 680, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();

            String Password=PA.getText();
            String FirstName=FN.getText();
            String LastName=LN.getText();
            String GENDER=Gender.getText();
            String Mobile=MO.getText();
            String Dob=DOB.getText();
            String Sem=SEM.getText();
            String Address=ADD.getText();
            String College=CN.getText();
            String UserName=UN.getText();
            String sql="update StudentInfo set Password=?,FirstName=?,LastName=?,Gender=?,Mobile=?,DOB=?,SEM=?,Address=?,College=? where UserName=? ";
            connection=DriverManager.getConnection(connectionURl,"Akash","Akash");

            ps=connection.prepareStatement(sql);

            ps.setString(1,Password);

            ps.setString(2,FirstName);
            ps.setString(3,LastName);
            ps.setString(4, GENDER);
            ps.setString(5,Mobile);
            ps.setString(6, Dob);
            ps.setString(7,Sem);
            ps.setString(8, Address);
            ps.setString(9,College);

            ps.setString(10, UserName);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Update successfully");

        }
        catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
            String UserName=UN.getText().toString();
            String sql="delete from StudentInfo where UserName=?";
            connection=DriverManager.getConnection(connectionURl,"Akash","Akash");
            ps=connection.prepareStatement(sql);
            ps.setString(1, UserName);
            ps.execute();

            JOptionPane.showMessageDialog(null,"The data has been Delete");

        }
        catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       StudentHome AL=new StudentHome();
        StudentHome.N.setText(this.PR.getText());
        AL.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEMActionPerformed

    private void PRPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PRPropertyChange
        // TODO add your handling code here:
          try
   {
       
      //this is used for transfer the data to another Frame
       String UNP=PR.getText();
       Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
       connection=DriverManager.getConnection(connectionURl,"Akash","Akash");
       String sql="select * from StudentInfo where UserName=?";
       ps=connection.prepareStatement(sql);
       ps.setString(1, UNP);
       rs=ps.executeQuery();
       while(rs.next())
       {
           UN.setText(rs.getString("UserName"));
           PA.setText(rs.getString("Password"));
            FN.setText(rs.getString("FirstName"));
           LN.setText(rs.getString("LastName"));
           Gender.setText(rs.getString("Gender"));
           MO.setText(rs.getString("Mobile"));
           DOB.setText(rs.getString("DOB"));
           SEM.setText(rs.getString("SEM"));
          CN.setText(rs.getString("College"));
          ADD.setText(rs.getString("Address"));
           
       }
       
   }
       catch(SQLException se)
        {
            se.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PRPropertyChange

    private void PRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PRFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PRFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADD;
    private javax.swing.JTextArea CN;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField LN;
    private javax.swing.JTextField MO;
    private javax.swing.JTextField PA;
    public static javax.swing.JLabel PR;
    private javax.swing.JTextField SEM;
    private javax.swing.JTextField UN;
    private javax.swing.JLabel UNP;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
